services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tin-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      PORT: 3000
    command: ["pm2-runtime", "ecosystem.config.cjs"]
    networks:
      - backend_net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend_net:
    driver: bridge