services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tin-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
    command: ["pm2-runtime", "ecosystem.config.cjs"]
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:

networks:
  backend_net:
    driver: bridge